[workspace]
members = [
    ".",
    "bughouse_console",
    "bughouse_wasm",
]

[package]
name = "bughouse_chess"
version = "0.1.0"
authors = ["Andrei Matveiakin <a.matveiakin@gmail.com>"]
edition = "2021"

[features]
strict = []  # treat warnings as a build error

[dependencies]
chain-cmp = "0.2.0"
derive-new = "0.5.9"
enum-map = "2.6.3"
git-version = "0.3.5"
hdrhistogram = "7.5.2"
indoc = "2.0.4"
instant = { version = "0.1.12", features = ["wasm-bindgen"] }
itertools = "0.11.0"
log = "0.4.20"
ndarray = { version = "0.15.6", features = ["serde"] }
rand = "0.8.5"
# Improvement potential: Use a static regex compiler to further reduce WASM size.
regex-lite = "0.1.0"
scopeguard = "1.2.0"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"
static_assertions = "1.1.0"
strum = { version = "0.25", features = ["derive"] }
time = { version = "0.3.29", features = ["formatting", "macros"] }

[dev-dependencies]
pretty_assertions = "1.4.0"
