[package]
name = "bughouse-chess"
version = "0.1.0"
authors = ["Andrei Matveiakin <a.matveiakin@gmail.com>"]
edition = "2021"

[dependencies]
derive-new = "0.5.9"
enum-map = "2.1.0"
# enum-map-derive = "*"  // !!!
itertools = "0.10.3"
