[package]
name = "bughouse-chess"
version = "0.1.0"
authors = ["Andrei Matveiakin <a.matveiakin@gmail.com>"]
edition = "2021"

[dependencies]
crossterm = "0.23.2"
console = "0.15.0"
derive-new = "0.5.9"
enum-map = "2.1.0"
itertools = "0.10.3"
lazy_static = "1.4.0"
rand = "0.8.5"
regex = "1.5.5"
