[workspace]
members = [
    ".",
    "bughouse_console",
    "bughouse_wasm",
]

[package]
name = "bughouse_chess"
version = "0.1.0"
authors = ["Andrei Matveiakin <a.matveiakin@gmail.com>"]
edition = "2021"

[dependencies]
chrono = { version = "0.4.19", features = ["wasmbind"] }
derive-new = "0.5.9"
enum-map = "2.1.0"
instant = { version = "0.1.12", features = ["wasm-bindgen"] }
itertools = "0.10.3"
lazy_static = "1.4.0"
rand = "0.8.5"
regex = "1.5.5"
scopeguard = "1.1.0"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
strum = { version = "0.24", features = ["derive"] }
