database_options: !Sqlite <DB-PATH>/bughouse.db
secret_database_options: !Sqlite <DB-PATH>/bughouse-secret.db
auth_options: !Google
  callback_is_https: true
  client_id_source: !Literal "<GOOGLE-CLIENT-ID>"
  client_secret_source: !File <SECRET-PATH>/google-client-secret
session_options: !WithSessions
  secret: !File <SECRET-PATH>/session-secret
  expire_in:
    secs: 2592000  # 30 days
    nanos: 0
static_content_url_prefix: ""
allowed_origin: !ThisSite https://bughouse.pro
