[package]
name = "bughouse_wasm"
version = "0.1.0"
authors = ["Andrei Matveiakin <a.matveiakin@gmail.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
enum-map = "2.1.0"
getrandom = { version = "0.2.6", features = ["js"] }
instant = { version = "0.1.12", features = [ "wasm-bindgen" ] }
serde_json = "1.0.79"
wasm-bindgen = "0.2.80"

# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
console_error_panic_hook = { version = "0.1.6", optional = true }

bughouse_chess = { path = ".." }

[dependencies.web-sys]
version = "0.3.57"
features = [
  'Document',
  'Element',
  'HtmlElement',
  'Node',
  'Window',
]

[dev-dependencies]
wasm-bindgen-test = "0.3.13"

# Improvement potential: Optimize WASM version for size. Note: simply uncommenting this gives:
#   warning: profiles for the non root package will be ignored, specify profiles at the workspace root
# [profile.release]
# opt-level = "s"  # optimize for small code size
