env:
  browser: true
  es2021: true
extends: eslint:recommended
plugins:
  - only-warn
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  no-unused-vars:
    - error
    - args: none
  semi:
    - error
    - always
